#! /bin/sh

# start sxhkd
sxhkd &

# colors
bspc config focused_border_color "#FBA922"

# set up monitors
bspc monitor DP-0 -d VI:6 VII:7 VIII:8 IX:9 X:10
bspc monitor DP-5 -d I:1 II:2 III:3 IV:4 V:5 

bspc config border_width         2
bspc config window_gap          30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# start polybar
killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
polybar -r left &
polybar -r right &
polybar -r bottom &
echo "Polybar launched..."

# autostart application rules
bspc rule -a "Termite" desktop='^1' follow=on focus=on
bspc rule -a "Chromium-browser" desktop='^6' follow=on focus=on
bspc rule -a "discord" desktop='^7' follow=off
bspc rule -a "Slack" desktop='^7' follow=off
bspc rule -a "Steam" desktop='^8' follow=off focus=off
bspc rule -a "csgo_linux64" desktop='^10' follow=off focus=off
wmname LG3D

# autostart applications
hsetroot -solid "#ffffff"
sleep 1
compton -b --config /home/alex/.config/compton/compton.conf
sleep 1
termite -e neofetch --hold &
sleep 1
termite -e 'bash -c "~/mine"' --hold &
sleep 1
termite -e gtop --hold &
sleep 1
discord &
sleep 2
slack &
sleep 2
chromium-browser &
sleep 2
steam &
sleep 5

# remove rules because --one-shot doesn't work
bspc rule -r "Termite" 
bspc rule -r "Chromium-browser"
bspc rule -r "discord"
bspc rule -r "Slack"
bspc rule -r "Steam" 

bspc desktop -f '^6'
